### PR TITLE
Make SAT thread-safe, improve performance and update SpotBugs

### LINKED ISSUE #200: Parallel builds using static-code-analysis get stuck and fail
Whenever I do a parallel build (`mvn clean install -T 1C`) of openHAB or ESH projects with static-code-analysis these builds get stuck and then after a timeout the build fails. 

When I run the same builds using `mvn clean install -T 1C -DskipChecks=true` these builds succeed.

I've succesfully used the Maven Checkstyle, PMD, Findbugs plugins on non-OH/ESH projects without these parallel build issues. Parallel builds save a lot of time when they work. 

The stacktraces suggest that `org.openhab.tools.analysis.report.ReportUtility` is not thread safe:

```
java.io.IOException: No such file or directory
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.openhab.tools.analysis.report.ReportUtility.generateSummaryByRules(ReportUtility.java:421)
	at org.openhab.tools.analysis.report.ReportUtility.execute(ReportUtility.java:223)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

```
[ERROR] TransformerException occcurred 
net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; Premature end of file.
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:418)
	at net.sf.saxon.event.Sender.send(Sender.java:214)
	at net.sf.saxon.event.Sender.send(Sender.java:50)
	at net.sf.saxon.Controller.transform(Controller.java:1611)
	at org.openhab.tools.analysis.report.ReportUtility.run(ReportUtility.java:264)
	at org.openhab.tools.analysis.report.ReportUtility.generateSummaryByRules(ReportUtility.java:428)
	at org.openhab.tools.analysis.report.ReportUtility.execute(ReportUtility.java:223)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.xml.sax.SAXParseException; Premature end of file.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:404)
	... 19 more
---------
org.xml.sax.SAXParseException; Premature end of file.
	at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:404)
	at net.sf.saxon.event.Sender.send(Sender.java:214)
	at net.sf.saxon.event.Sender.send(Sender.java:50)
	at net.sf.saxon.Controller.transform(Controller.java:1611)
	at org.openhab.tools.analysis.report.ReportUtility.run(ReportUtility.java:264)
	at org.openhab.tools.analysis.report.ReportUtility.generateSummaryByRules(ReportUtility.java:428)
	at org.openhab.tools.analysis.report.ReportUtility.execute(ReportUtility.java:223)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:200)
	at org.apache.maven.lifecycle.internal.builder.multithreaded.MultiThreadedBuilder$1.call(MultiThreadedBuilder.java:196)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

````
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:45 min (Wall Clock)
[INFO] Finished at: 2017-09-21T22:06:12+02:00
Timeout: sub-process interrupted[INFO] Final Memory: 156M/2026M

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.openhab.tools:static-code-analysis:0.3.0:findbugs (default) on project org.openhab.binding.hdanywhere: Unable to execute mojo: Execution null of goal com.github.hazendaz.spotbugs:spotbugs-maven-plugin:3.0.6:findbugs failed: Timeout: killed the sub-process -> [Help 1]
[ERROR] Failed to execute goal org.openhab.tools:static-code-analysis:0.3.0:findbugs (default) on project org.openhab.binding.folding: Unable to execute mojo: Execution null of goal com.github.hazendaz.spotbugs:spotbugs-maven-plugin:3.0.6:findbugs failed: Timeout: killed the sub-process -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.openhab.binding.hdanywhere
Timeout: sub-process interrupted
org.apache.tools.ant.ExitException: Permission ("java.lang.RuntimePermission" "exitVM") was not granted.
	at org.apache.tools.ant.types.Permissions$MySM.checkExit(Permissions.java:194)
	at java.lang.Runtime.exit(Runtime.java:107)
	at java.lang.System.exit(System.java:971)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:358)
Exception in thread "main" org.apache.tools.ant.ExitException: Permission ("java.lang.RuntimePermission" "exitVM") was not granted.
	at org.apache.tools.ant.types.Permissions$MySM.checkExit(Permissions.java:194)
	at java.lang.Runtime.exit(Runtime.java:107)
	at java.lang.System.exit(System.java:971)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:364)
Timeout: sub-process interrupted
Timeout: sub-process interrupted
Timeout: sub-process interrupted
Timeout: sub-process interrupted
Timeout: sub-process interrupted
```

### PR DESCRIPTION
**Pull request by wborn**
This PR makes the SAT Maven plugins thread-safe when used in parallel Maven builds.

Fixes the following theading issues:

* SpotBugs is only thread-safe when it uses the forking mode which is enabled by default but disabled in the SAT configuration.
  SpotBugs uses Apache Commons BCEL as dependency which is not thread-safe. Forking the SpotBugs execution works around this issue.
  Without forking enabled parallel builds using SpotBugs will also lock up (see https://github.com/spotbugs/spotbugs-maven-plugin/issues/104).
* Use JVM singleton merge/summary locks for synchronizing the SAT summary report updates.
  Because multiple classloaders are used in Maven builds, it's not possible to use a static lock for synchronization in the ReportUtility Mojo.

The Mojos have also been marked as threadSafe so Maven no longer shows warnings when they are executed in parallel.

For the SpotBugs updates see:

* Spotbugs 3.1.12 release notes:
  https://github.com/spotbugs/spotbugs/blob/3.1.12/CHANGELOG.md#3112---2019-02-28
* findbugs-slf4j 1.5.0 release notes:
  https://github.com/KengoTODA/findbugs-slf4j/blob/master/CHANGELOG.md#150---2019-07-04

The errors resulting from the findbugs-slf4j upgrade have already been fixed by:

* openhab/openhab-core#1213
* openhab/openhab2-addons#6394

Performance has also been improved considerably by moving the HTML summary generation to an extension.
This way SAT can periodically update the HTML summary instead of continuously.
Updating the HTML summaries can take 20 seconds or more when there are many findings.

Fixes #200

---

These changes speed up both single threaded and parallel builds using SAT considerably!

Below are some openhab2-addons build results on my quad core i7-6700K (no tests because they fail, [openhab/openhab2-addons#6408](https://github.com/openhab/openhab2-addons/issues/6408)):

| SAT version    | Command                                 | Duration  | Speedup |
|----------------|-----------------------------------------|-----------|---------|
| 0.8.0          | `mvn clean install -DskipTests`         | 44:33 min | 1.00x   |
| 0.9.0-SNAPSHOT | `mvn clean install -DskipTests`         | 23:05 min | 1.93x   |
| 0.9.0-SNAPSHOT | `mvn clean install -DskipTests -T 1.5C` | 13:31 min | 3.29x   |

The parallel builds max out all CPUs. I can only imagine how fast a parallel build will be on a machine with 16 cores. :-)

The extension should be added to the `<build>` section in POMs, see https://github.com/wborn/openhab2-addons/commit/fe73013b8906b2b38a18ef4694f5e9856ede65fd.

### CODE REVIEW

File: sat-extension/src/main/java/org/openhab/tools/analysis/report/SummaryReportExecutionListener.java [hunk 1]
```diff
@@ -0,0 +1,265 @@
...
+
+        public void incrementalUpdate() {
+            executor.submit(() -> {
+                if (htmlGeneration == SummaryHtmlGeneration.CONTINUOUS
+                        || (htmlGeneration == SummaryHtmlGeneration.PERIODIC
+                                && Instant.now().isAfter(lastUpdate.plusSeconds(htmlGenerationPeriod)))) {
+                    File latestSummaryReport = update();
+
+                    if (logger.isDebugEnabled()) {
+                        logger.debug("Updated static code analysis summary report in:");
```
Comment (martinvw) [inline sat-extension/src/main/java/org/openhab/tools/analysis/report/SummaryReportExecutionListener.java]: what about: 

```java
logger.debug("Updated static code analysis summary report in: {}", latestSummaryReport.toURI());
```

You can then leave out the `isDebugEnabled` check

Comment (martinvw) [reply sat-extension/src/main/java/org/openhab/tools/analysis/report/SummaryReportExecutionListener.java]: Nevermind its no such logger :-(

**Comment by martinvw** [comment]
Nice!

File: sat-extension/src/main/java/org/openhab/tools/analysis/report/SummaryReportExecutionListener.java (hunk 1 above)
Comment (wborn) [reply sat-extension/src/main/java/org/openhab/tools/analysis/report/SummaryReportExecutionListener.java]: Yes there are Plexus and Maven loggers instead of SLF4J which also makes it sometimes difficult to reuse code. :worried:

**Comment by wborn** [comment]
It would be awesome to reduce our build times by having this in a new SAT release @openhab/sat-maintainers. :stuck_out_tongue_winking_eye:

File: sat-extension/src/main/java/org/openhab/tools/analysis/report/SummaryReportHtmlGenerator.java [hunk 2]
```diff
@@ -0,0 +1,155 @@
...
+import javax.xml.transform.TransformerException;
+import javax.xml.transform.TransformerFactory;
+import javax.xml.transform.stream.StreamResult;
+import javax.xml.transform.stream.StreamSource;
+
+import org.codehaus.plexus.component.annotations.Component;
+import org.codehaus.plexus.component.annotations.Requirement;
+import org.codehaus.plexus.logging.Logger;
+
+import com.google.common.io.Files;
```
Comment (Hilbrand) [inline sat-extension/src/main/java/org/openhab/tools/analysis/report/SummaryReportHtmlGenerator.java]: Can't this be `java.nio.file.Files`?

Comment (wborn) [reply sat-extension/src/main/java/org/openhab/tools/analysis/report/SummaryReportHtmlGenerator.java]: I also wasn't happy with this and tried changing them (it's code from the original Mojo) but for some reason it didn't work well so I left it as is. I'll see if I can conquer this in a second attempt.

File: sat-extension/pom.xml [hunk 3]
```diff
@@ -0,0 +1,89 @@
+<?xml version="1.0" encoding="UTF-8"?>
+<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
+  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
```
[the remark this answers is not in the document]
Comment (wborn) [reply sat-extension/pom.xml]: I see many other SAT POMs need to be updated to so I'll correct this one in this PR and come up with a PR for the others.

**Comment by wborn** [comment]
Also I just noticed there are still some threading issues on Java 8 so I'll look into that too. They aren't there on Java 11 to which I try to default these days. Sometimes I switch back for other projects and then end up testing openHAB code with Java 8 too.

File: sat-extension/src/main/java/org/openhab/tools/analysis/report/SummaryReportHtmlGenerator.java [hunk 4]
```diff
@@ -0,0 +1,155 @@
...
+    }
+
+    private void run(final String xslt, final File input, final File output) {
+        try (FileOutputStream outputStream = new FileOutputStream(output)) {
+            if (logger.isDebugEnabled()) {
+                logger.debug(MessageFormat.format("{0}  > {1} >  {2}", input, xslt, output));
+            }
+
+            // Process the Source into a Transformer Object
+            final InputStream inputStream = contextClassLoader.getResourceAsStream(xslt);
```
[the remark this answers is not in the document]
Comment (wborn) [reply sat-extension/src/main/java/org/openhab/tools/analysis/report/SummaryReportHtmlGenerator.java]: I will move them to a try-with-resources statement to be sure there won't be any (future) issues. Usually there is no explicit need to close the streams.

See: https://docs.oracle.com/javase/8/docs/api/java/util/stream/Stream.html

> Streams have a BaseStream.close() method and implement AutoCloseable, but nearly all stream instances do not actually need to be closed after use. Generally, only streams whose source is an IO channel (such as those returned by Files.lines(Path, Charset)) will require closing. Most streams are backed by collections, arrays, or generating functions, which require no special resource management. (If a stream does require closing, it can be declared as a resource in a try-with-resources statement.)

File: sat-extension/src/main/java/org/openhab/tools/analysis/report/SummaryReportHtmlGenerator.java (hunk 2 above)
Comment (wborn) [reply sat-extension/src/main/java/org/openhab/tools/analysis/report/SummaryReportHtmlGenerator.java]: For unknown reasons it seems to work fine now (Java 11).

File: sat-extension/pom.xml (hunk 3 above)
[the remark this answers is not in the document]
Comment (wborn) [reply sat-extension/pom.xml]: The others are updated in https://github.com/openhab/static-code-analysis/pull/369.

**Comment by Hilbrand** [comment]
Do you still want to look into the java8 issues or can I merge this?

> I can only imagine how fast a parallel build will be on a machine with 16 cores. :-)

Darn. Now I got distracted browsing for a new computer :smile:

**Comment by wborn** [comment]
I am still looking into how well this works for Java 8. 

Yes I'm also feeling my CPU is getting dated. But they are adding more cores every year so I'll just hold on for it a bit longer to get a better deal. ;-)

**Comment by kaikreuzer** [comment]
> It would be awesome to reduce our build times by having this in a new SAT release

Absolutely! I just didn't react on it before the release as I didn't want to risk anything ;-)
But now it is definitely time to benefit from this great work!

> I am still looking into how well this works for Java 8.

Why? In the light of https://github.com/openhab/openhab-core/issues/1287, I think it would be ok if we only support Java 11 (and keep the 2.5.x build on the current SAT version).

**Comment by wborn** [comment]
Apparently these FileChannel locks can be buggy on Java 8 and behave differently between OS-es.
So I did some more searching and found this [Stack Overflow post](https://stackoverflow.com/questions/15156840/singleton-class-with-several-different-classloaders).

It's possible get a singleton over different class loaders by always loading a class using the same class loader and a lot of reflection. I tried that and it didn't work well and all the reflection didn't make it nice code.

The other option is by just adding the singleton to the System properties. It may not be ideal but it does work on Java 8 and Java 11 and it results in less and nicer code.

**Comment by kaikreuzer** [comment]
Awesome work, @wborn!

**Comment by kaikreuzer** [comment]
New version https://github.com/openhab/static-code-analysis/releases/tag/0.9.0 has been released!

**Comment by wborn** [comment]
Thanks for making the new release! :+1:
